### ISSUE TITLE
weight is not moved to correct device for Poly1FocalLoss

### ISSUE THREAD

**Issue by DannieSheng** [veritable-tech/pytorch-lightning-spells#2]
When using Poly1FocalLoss with the `weight` option, it is realized that the weight is not moved to the correct device.
It can be fixed by adding the coming part to the `forward` method of `Poly1FocalLoss`
```
if self.weight is not None:
    self.weight = self.weight.to(logits.device)
```

**Comment by ceshine** [comment]
@DannieSheng Thanks for reporting the issue. It has been fixed in this commit: https://github.com/veritable-tech/pytorch-lightning-spells/commit/cec335d636d925535c21a1cf8f14860a4b746712
